[package]
name = "tmfs-join"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
either-id = { path = "../either-id" }
langspec = { path = "../langspec" }
syn = { workspace = true }
