/// generated by [term_unspecialized_impl_gen::generate]
pub mod term_impls {
    /// generated by [term_unspecialized_impl_gen::gen_heap_impl]
    impl crate::extension_of::Heap for term_unspecialized::TermHeap {
        type Plus = term_unspecialized::Term<
            0x9f0faf85517fedd16f90edf02c63c231,
            tymetafuncspec_core::Core,
            Self,
        >;
        type LeftOperand = term_unspecialized::Term<
            0xc99c8d0f5da794148c5600fd230ad5e1,
            tymetafuncspec_core::Core,
            Self,
        >;
        type RightOperand = term_unspecialized::Term<
            0x95311c98aac8608e9c82d5c1d5f58cde,
            tymetafuncspec_core::Core,
            Self,
        >;
        type F = term_unspecialized::Term<
            0xccebad3393972e4a79bf233aa9bae29f,
            tymetafuncspec_core::Core,
            Self,
        >;
        type Sum = term_unspecialized::Term<
            0xd297f2f5c7e2ce43a012d45f7416c361,
            tymetafuncspec_core::Core,
            Self,
        >;
        type Nat = term_unspecialized::Term<
            0xf76b1cf2f6af4342c236152a66a64e3e,
            tymetafuncspec_core::Core,
            Self,
        >;
    }
    /// generated by [term_unspecialized_impl_gen::gen_owned_mod]
    pub mod owned_impls {
        impl crate::extension_of::owned::Plus
        for <term_unspecialized::TermHeap as crate::extension_of::Heap>::Plus {}
        impl crate::extension_of::owned::LeftOperand
        for <term_unspecialized::TermHeap as crate::extension_of::Heap>::LeftOperand {}
        impl crate::extension_of::owned::RightOperand
        for <term_unspecialized::TermHeap as crate::extension_of::Heap>::RightOperand {}
        impl crate::extension_of::owned::F
        for <term_unspecialized::TermHeap as crate::extension_of::Heap>::F {}
        impl crate::extension_of::owned::Sum
        for <term_unspecialized::TermHeap as crate::extension_of::Heap>::Sum {}
        impl crate::extension_of::owned::Nat
        for <term_unspecialized::TermHeap as crate::extension_of::Heap>::Nat {}
    }
    /// generated by [term_unspecialized_impl_gen::gen_ccf_mod]
    pub mod ccf_impls {}
    /// generated by [term_unspecialized_impl_gen::gen_mct_mod]
    pub mod mct_impls {}
}
/// generated by [term_trait_gen::generate]
pub mod extension_of {
    /// generated by [term_trait_gen::heap_trait]
    pub trait Heap: term::SuperHeap<
            tymetafuncspec_core::SetHeapBak<Self, Self::Nat>,
        > + term::SuperHeap<
            tymetafuncspec_core::BoundedNatHeapBak<Self>,
        > + term::SuperHeap<
            tymetafuncspec_core::IdxBoxHeapBak<Self, Self::F>,
        > + term::SuperHeap<
            tymetafuncspec_core::IdxBoxHeapBak<Self, Self::Plus>,
        > + Sized {
        type Plus: crate::extension_of::owned::Plus<Heap = Self>;
        type LeftOperand: crate::extension_of::owned::LeftOperand<Heap = Self>;
        type RightOperand: crate::extension_of::owned::RightOperand<Heap = Self>;
        type F: crate::extension_of::owned::F<Heap = Self>;
        type Sum: crate::extension_of::owned::Sum<Heap = Self>;
        type Nat: crate::extension_of::owned::Nat<Heap = Self>;
    }
    /// generated by [term_trait_gen::owned::generate]
    pub mod owned {
        pub trait Plus: term::Heaped + term::CanonicallyConstructibleFrom<
                (
                    <<Self as term::Heaped>::Heap as crate::extension_of::Heap>::LeftOperand,
                    <<Self as term::Heaped>::Heap as crate::extension_of::Heap>::RightOperand,
                ),
            >
        where
            <Self as term::Heaped>::Heap: crate::extension_of::Heap,
        {}
        pub trait LeftOperand: term::Heaped + term::CanonicallyConstructibleFrom<
                (<<Self as term::Heaped>::Heap as crate::extension_of::Heap>::Nat,),
            >
        where
            <Self as term::Heaped>::Heap: crate::extension_of::Heap,
        {}
        pub trait RightOperand: term::Heaped + term::CanonicallyConstructibleFrom<
                (<<Self as term::Heaped>::Heap as crate::extension_of::Heap>::Nat,),
            >
        where
            <Self as term::Heaped>::Heap: crate::extension_of::Heap,
        {}
        pub trait F: term::Heaped + term::CanonicallyConstructibleFrom<
                (<<Self as term::Heaped>::Heap as crate::extension_of::Heap>::Nat,),
            >
        where
            <Self as term::Heaped>::Heap: crate::extension_of::Heap,
        {}
        pub trait Sum: term::Heaped + term::CanonicallyConstructibleFrom<
                (
                    tymetafuncspec_core::Set<
                        <Self as term::Heaped>::Heap,
                        <<Self as term::Heaped>::Heap as crate::extension_of::Heap>::Nat,
                    >,
                ),
            >
        where
            <Self as term::Heaped>::Heap: crate::extension_of::Heap,
        {}
        pub trait Nat: term::Heaped + term::CanonicallyConstructibleFrom<
                (tymetafuncspec_core::BoundedNat<<Self as term::Heaped>::Heap>,),
            > + term::CanonicallyConstructibleFrom<
                (
                    tymetafuncspec_core::IdxBox<
                        <Self as term::Heaped>::Heap,
                        <<Self as term::Heaped>::Heap as crate::extension_of::Heap>::F,
                    >,
                ),
            > + term::CanonicallyConstructibleFrom<
                (
                    tymetafuncspec_core::IdxBox<
                        <Self as term::Heaped>::Heap,
                        <<Self as term::Heaped>::Heap as crate::extension_of::Heap>::Plus,
                    >,
                ),
            >
        where
            <Self as term::Heaped>::Heap: crate::extension_of::Heap,
        {}
    }
    /// generated by [term_trait_gen::reference::generate]
    pub mod reference {}
}
