[dependencies.ccf]
path = "../.././ccf"

[dependencies.fib]
path = "../fib"

[dependencies.term]
path = "../.././term"

[dependencies.term-pattern-match-strategy-provider-impl-gen]
path = "../.././term-pattern-match-strategy-provider-impl-gen"

[dependencies.term-specialized-gen]
path = "../.././term-specialized-gen"

[dependencies.term-specialized-impl-gen]
path = "../.././term-specialized-impl-gen"

[dependencies.term-trait-gen]
path = "../.././term-trait-gen"

[dependencies.tymetafuncspec-core]
path = "../.././tymetafuncspec-core"

[dependencies.typenum]
workspace = true

[dependencies.unparse-adt]
path = "../.././unparse-adt"

[dependencies.words]
path = "../.././words"

[package]
edition = "2024"
name = "fib-ds"
version = "0.0.0"
