[package]
name = "parse"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = { version = "7.4.0", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
term = { version = "0.1.0", path = "../term" }
thiserror = "2.0.11"
unicode-segmentation = "1.12.0"
