[package]
name = "parse"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
miette = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
unicode-segmentation = { workspace = true }
term = { path = "../term" }
