[workspace]

resolver = "2"
members = [ "extensionof-gen", "idxbased-extensionof-gen","langdatastructure-gen", "langspec", "langspec-examples", "langspec-gen-util", "pattern", "refbased-extensionof-gen", "sexprfmt"]
