[workspace]

resolver = "2"
members = [
    "related-gen",
    "idxbased-related-gen",
    "langdatastructure-gen",
    "langserde",
    "langspec",
    "langspec-examples",
    "langspec-gen-util",
    "langspec-join",
    "langspec-sumextend",
    "pattern",
    "refbased-related-gen",
    "term-of-gen",
    "sexprfmt",
    "term-of",
    "pattern-lang",
]
