[workspace]

resolver = "2"
cargo-features = ["edition2024"]

members = [
    "langspec-gen-util",
    "langspec-examples",
    "langspec-join",
    "langspec-sumextend",
    "langspec",
    "sexprfmt",
    "term-specialized-gen",
    "term-trait-gen",
    "term",
    "tymetafuncspec-core", "term-specialized-impl-gen", "term-unspecialized", "term-unspecialized-impl-gen",
    # "bounded-slice",
    # "idxbased-related-gen",
    # "langserde",
    # "langspec-gen-util",
    # "pattern-lang",
    # "pattern",
    # "refbased-related-gen",
    # "related-gen",
    # "term-of-gen",
]
