[package]
name = "abstracted-langspec-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
langspec = { version = "0.1.0", path = "../langspec" }
langspec-gen-util = { version = "0.1.0", path = "../langspec-gen-util" }
proc-macro2 = "1.0.92"
syn = "2.0.90"
