[package]
name = "std-parse-error"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
langspec = { path = "../../langspec" }
parse = { path = "../../parse" }
term = { path = "../../term" }
tree-identifier = { path = "../../tree-identifier" }
serde = { workspace = true }
derivative = { workspace = true }
serde_json = { workspace = true }
syn = { workspace = true }
