[package]
name = "langspec-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
langspec = { version = "0.1.0", path = "../langspec" }
lexpr = { version = "0.2.7", default-features = false }
serde-lexpr = "0.1.3"
typed-index-collections = "3.1.0"
