[package]
name = "pattern-specialized"
version.workspace = true
edition.workspace = true
description = "Generics and traits for monomorphized/statically-typed pattern representations"

[dependencies]
pattern-dyn.path = "../pattern-dyn"
ccf = { path = "../ccf" }
conslist = { path = "../conslist" }
pmsp = { path = "../pmsp" }
