[dependencies.term]
path = "../../term"

[dependencies.term-trait-gen]
path = "../../term-trait-gen"

[dependencies.tymetafuncspec-core]
path = "../../tymetafuncspec-core"

[dependencies.words]
path = "../../words"

[package]
edition = "2024"
name = "fib"
version = "0.0.0"
