[package]
name = "term"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
fn-traits = { workspace = true }
take_mut = { workspace = true }
type-equals.workspace = true
typenum = { workspace = true }
