[package]
name = "term"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
take_mut = { workspace = true }
type-equals = { workspace = true }
typenum = { workspace = true }
