[package]
name = "term"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
langspec = { path = "../langspec" }
proc-macro2 = { workspace = true }
syn = { workspace = true }
take_mut = { workspace = true }
twox-hash = { workspace = true }
type-equals = { workspace = true }
typenum = { workspace = true }
