[package]
name = "term"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
fn-traits = { workspace = true }
take-mut.path = "../take-mut"
type-equals.workspace = true
typenum = { workspace = true }
