[package]
name = "refbased-extensionof-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
extensionof-gen = { version = "0.1.0", path = "../extensionof-gen" }
langdatastructure-gen = { version = "0.1.0", path = "../langdatastructure-gen" }
langspec = { version = "0.1.0", path = "../langspec" }
langspec-gen-util = { version = "0.1.0", path = "../langspec-gen-util" }
prettyplease = "0.2.25"
quote = "1.0.37"
syn = "2.0.87"

[dev-dependencies]
expect-test = "1.5.0"
langspec-examples = { path = "../langspec-examples" }
