[package]
name = "tree-token"
version.workspace = true
edition.workspace = true

[dependencies]
arbitrary.workspace = true
expect-test.workspace = true
proc-macro2.workspace = true
rand.workspace = true
syn.workspace = true
thiserror.workspace = true
