/// generated by [term_trait_gen::generate]
#[rustfmt::skip]
pub mod extension_of {
    use tymetafuncspec_core::Set;
    use tymetafuncspec_core::IdxBox;
    use term::MapsTmf;
    use tymetafuncspec_core::BoundedNatHeapBak;
    use crate::extension_of::words as eow;
    use tymetafuncspec_core::SetHeapBak;
    use tymetafuncspec_core::IdxBoxHeapBak;
    use term::SuperHeap;
    use crate::extension_of::owned as eoo;
    use tymetafuncspec_core::BoundedNat;
    /// generated by [term_trait_gen::heap_trait]
    #[rustfmt::skip]
    pub trait Heap: Sized + MapsTmf<
            eow::L,
            Set<Self, Self::Nat>,
        > + MapsTmf<
            eow::L,
            BoundedNat<Self>,
        > + MapsTmf<
            eow::L,
            IdxBox<Self, Self::F>,
        > + MapsTmf<
            eow::L,
            IdxBox<Self, Self::Plus>,
        > + MapsTmf<
            eow::L,
            IdxBox<Self, Self::Sum>,
        > + SuperHeap<
            SetHeapBak<Self, Self::Nat>,
        > + SuperHeap<
            BoundedNatHeapBak<Self>,
        > + SuperHeap<
            IdxBoxHeapBak<Self, Self::F>,
        > + SuperHeap<
            IdxBoxHeapBak<Self, Self::Plus>,
        > + SuperHeap<IdxBoxHeapBak<Self, Self::Sum>> {
        type Plus: eoo::Plus<Heap = Self>;
        type LeftOperand: eoo::LeftOperand<Heap = Self>;
        type RightOperand: eoo::RightOperand<Heap = Self>;
        type F: eoo::F<Heap = Self>;
        type Sum: eoo::Sum<Heap = Self>;
        type Nat: eoo::Nat<Heap = Self>;
    }
    /// generated by [term_trait_gen::owned::generate]
    #[rustfmt::skip]
    pub mod owned {
        use crate::extension_of as eo;
        use tymetafuncspec_core::Set;
        use tymetafuncspec_core::IdxBox;
        use term::Heaped;
        use tymetafuncspec_core::BoundedNat;
        use term::CanonicallyConstructibleFrom;
        pub trait Plus: Heaped + CanonicallyConstructibleFrom<
                <Self as Heaped>::Heap,
                (
                    <<Self as Heaped>::Heap as eo::Heap>::LeftOperand,
                    (<<Self as Heaped>::Heap as eo::Heap>::RightOperand, ()),
                ),
            >
        where
            <Self as Heaped>::Heap: eo::Heap,
        {}
        pub trait LeftOperand: Heaped + CanonicallyConstructibleFrom<
                <Self as Heaped>::Heap,
                (<<Self as Heaped>::Heap as eo::Heap>::Nat, ()),
            >
        where
            <Self as Heaped>::Heap: eo::Heap,
        {}
        pub trait RightOperand: Heaped + CanonicallyConstructibleFrom<
                <Self as Heaped>::Heap,
                (<<Self as Heaped>::Heap as eo::Heap>::Nat, ()),
            >
        where
            <Self as Heaped>::Heap: eo::Heap,
        {}
        pub trait F: Heaped + CanonicallyConstructibleFrom<
                <Self as Heaped>::Heap,
                (<<Self as Heaped>::Heap as eo::Heap>::Nat, ()),
            >
        where
            <Self as Heaped>::Heap: eo::Heap,
        {}
        pub trait Sum: Heaped + CanonicallyConstructibleFrom<
                <Self as Heaped>::Heap,
                (
                    Set<
                        <Self as Heaped>::Heap,
                        <<Self as Heaped>::Heap as eo::Heap>::Nat,
                    >,
                    (),
                ),
            >
        where
            <Self as Heaped>::Heap: eo::Heap,
        {}
        pub trait Nat: Heaped + CanonicallyConstructibleFrom<
                <Self as Heaped>::Heap,
                (BoundedNat<<Self as Heaped>::Heap>, ()),
            > + CanonicallyConstructibleFrom<
                <Self as Heaped>::Heap,
                (
                    IdxBox<
                        <Self as Heaped>::Heap,
                        <<Self as Heaped>::Heap as eo::Heap>::F,
                    >,
                    (),
                ),
            > + CanonicallyConstructibleFrom<
                <Self as Heaped>::Heap,
                (
                    IdxBox<
                        <Self as Heaped>::Heap,
                        <<Self as Heaped>::Heap as eo::Heap>::Plus,
                    >,
                    (),
                ),
            > + CanonicallyConstructibleFrom<
                <Self as Heaped>::Heap,
                (
                    IdxBox<
                        <Self as Heaped>::Heap,
                        <<Self as Heaped>::Heap as eo::Heap>::Sum,
                    >,
                    (),
                ),
            >
        where
            <Self as Heaped>::Heap: eo::Heap,
        {}
    }
    /// generated by [words::words_mod]
    #[rustfmt::skip]
    pub mod words {
        pub struct L;
        pub mod sorts {
            pub struct Plus;
            pub struct LeftOperand;
            pub struct RightOperand;
            pub struct F;
            pub struct Sum;
            pub struct Nat;
        }
    }
}
