[package]
name = "either-id"
version = "0.1.0"
edition = "2021"

[dependencies]
functor_derive = "0.4.3"
langspec = { version = "0.1.0", path = "../langspec" }
serde = { version = "1.0.217", features = ["derive"] }
syn = "2.0.96"
