[package]
name = "either-id"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
functor_derive = "0.4.3"
langspec = { path = "../langspec" }
serde = { version = "1.0.219", features = ["derive"] }
syn = "2.0.100"
