[package]
name = "unparse-adt"
version.workspace = true
edition.workspace = true

[dependencies]
bumpalo.workspace = true
ccf = { version = "0.1.0", path = "../ccf" }
parse-adt = { version = "0.1.0", path = "../parse-adt" }
pmsp = { version = "0.1.0", path = "../pmsp" }
term = { version = "0.1.0", path = "../term" }
tymetafuncspec-core = { version = "0.1.0", path = "../tymetafuncspec-core" }
typenum.workspace = true
visit = { version = "0.1.0", path = "../visit" }
words = { version = "0.1.0", path = "../words" }
