/// generated by [term_specialized_gen::generate]
pub mod data_structure {
    /// generated by [term_specialized_gen::gen_heap]
    #[derive(Default)]
    pub struct Heap {
        set: crate::data_structure::heap::set::Bak,
        nat_lit: crate::data_structure::heap::nat_lit::Bak,
        idx_box: crate::data_structure::heap::idx_box::Bak,
    }
    /// generated by [term_specialized_gen::gen_heap]
    pub mod heap {
        /// generated by [term_specialized_gen::gen_modules_with_prefix]
        #[derive(Default)]
        pub struct Bak {
            pub set: crate::data_structure::heap::set::Bak,
            pub nat_lit: crate::data_structure::heap::nat_lit::Bak,
            pub idx_box: crate::data_structure::heap::idx_box::Bak,
        }
        /// generated by [term_specialized_gen::gen_modules_with_prefix]
        pub mod set {
            /// generated by [term_specialized_gen::gen_modules_with_prefix]
            #[derive(Default)]
            pub struct Bak {
                pub nat: crate::data_structure::heap::set::nat::Bak,
            }
            /// generated by [term_specialized_gen::gen_modules_with_prefix]
            pub mod nat {
                /// generated by [term_specialized_gen::gen_heapbak_module]
                #[derive(Default)]
                pub struct Bak(
                    pub tymetafuncspec_core::SetHeapBak<
                        crate::data_structure::Heap,
                        crate::data_structure::Nat,
                    >,
                );
            }
        }
        /// generated by [term_specialized_gen::gen_modules_with_prefix]
        pub mod nat_lit {
            /// generated by [term_specialized_gen::gen_heapbak_module]
            #[derive(Default)]
            pub struct Bak(
                pub tymetafuncspec_core::BoundedNatHeapBak<crate::data_structure::Heap>,
            );
        }
        /// generated by [term_specialized_gen::gen_modules_with_prefix]
        pub mod idx_box {
            /// generated by [term_specialized_gen::gen_modules_with_prefix]
            #[derive(Default)]
            pub struct Bak {
                pub f: crate::data_structure::heap::idx_box::f::Bak,
                pub plus: crate::data_structure::heap::idx_box::plus::Bak,
                pub sum: crate::data_structure::heap::idx_box::sum::Bak,
            }
            /// generated by [term_specialized_gen::gen_modules_with_prefix]
            pub mod f {
                /// generated by [term_specialized_gen::gen_heapbak_module]
                #[derive(Default)]
                pub struct Bak(
                    pub tymetafuncspec_core::IdxBoxHeapBak<
                        crate::data_structure::Heap,
                        crate::data_structure::F,
                    >,
                );
            }
            /// generated by [term_specialized_gen::gen_modules_with_prefix]
            pub mod plus {
                /// generated by [term_specialized_gen::gen_heapbak_module]
                #[derive(Default)]
                pub struct Bak(
                    pub tymetafuncspec_core::IdxBoxHeapBak<
                        crate::data_structure::Heap,
                        crate::data_structure::Plus,
                    >,
                );
            }
            /// generated by [term_specialized_gen::gen_modules_with_prefix]
            pub mod sum {
                /// generated by [term_specialized_gen::gen_heapbak_module]
                #[derive(Default)]
                pub struct Bak(
                    pub tymetafuncspec_core::IdxBoxHeapBak<
                        crate::data_structure::Heap,
                        crate::data_structure::Sum,
                    >,
                );
            }
        }
    }
    /// generated by [term_specialized_gen::gen_heap]
    pub mod superheap {
        term::impl_superheap!(
            crate ::data_structure::Heap; tymetafuncspec_core::SetHeapBak < crate
            ::data_structure::Heap, crate ::data_structure::Nat >; set nat
        );
        term::impl_superheap!(
            crate ::data_structure::Heap; tymetafuncspec_core::BoundedNatHeapBak < crate
            ::data_structure::Heap, >; nat_lit
        );
        term::impl_superheap!(
            crate ::data_structure::Heap; tymetafuncspec_core::IdxBoxHeapBak < crate
            ::data_structure::Heap, crate ::data_structure::F >; idx_box f
        );
        term::impl_superheap!(
            crate ::data_structure::Heap; tymetafuncspec_core::IdxBoxHeapBak < crate
            ::data_structure::Heap, crate ::data_structure::Plus >; idx_box plus
        );
        term::impl_superheap!(
            crate ::data_structure::Heap; tymetafuncspec_core::IdxBoxHeapBak < crate
            ::data_structure::Heap, crate ::data_structure::Sum >; idx_box sum
        );
    }
    #[derive(Clone, Copy)]
    pub struct Plus {
        pub left_operand: crate::data_structure::LeftOperand,
        pub right_operand: crate::data_structure::RightOperand,
    }
    #[derive(Clone, Copy)]
    pub struct LeftOperand {
        pub nat: crate::data_structure::Nat,
    }
    #[derive(Clone, Copy)]
    pub struct RightOperand {
        pub nat: crate::data_structure::Nat,
    }
    #[derive(Clone, Copy)]
    pub struct F {
        pub nat: crate::data_structure::Nat,
    }
    #[derive(Clone, Copy)]
    pub struct Sum {
        pub set: tymetafuncspec_core::Set<
            crate::data_structure::Heap,
            crate::data_structure::Nat,
        >,
    }
    #[derive(Clone, Copy)]
    pub enum Nat {
        NatLit(tymetafuncspec_core::BoundedNat<crate::data_structure::Heap>),
        F(
            tymetafuncspec_core::IdxBox<
                crate::data_structure::Heap,
                crate::data_structure::F,
            >,
        ),
        Plus(
            tymetafuncspec_core::IdxBox<
                crate::data_structure::Heap,
                crate::data_structure::Plus,
            >,
        ),
        Sum(
            tymetafuncspec_core::IdxBox<
                crate::data_structure::Heap,
                crate::data_structure::Sum,
            >,
        ),
    }
    /// generated by [term_specialized_gen::gen_heaped_impls]
    pub mod heaped {
        /// generated by [term_specialized_gen::gen_heaped_impls::heaped_impl]
        impl term::Heaped for crate::data_structure::Plus {
            type Heap = crate::data_structure::Heap;
        }
        /// generated by [term_specialized_gen::gen_heaped_impls::heaped_impl]
        impl term::Heaped for crate::data_structure::LeftOperand {
            type Heap = crate::data_structure::Heap;
        }
        /// generated by [term_specialized_gen::gen_heaped_impls::heaped_impl]
        impl term::Heaped for crate::data_structure::RightOperand {
            type Heap = crate::data_structure::Heap;
        }
        /// generated by [term_specialized_gen::gen_heaped_impls::heaped_impl]
        impl term::Heaped for crate::data_structure::F {
            type Heap = crate::data_structure::Heap;
        }
        /// generated by [term_specialized_gen::gen_heaped_impls::heaped_impl]
        impl term::Heaped for crate::data_structure::Sum {
            type Heap = crate::data_structure::Heap;
        }
        /// generated by [term_specialized_gen::gen_heaped_impls::heaped_impl]
        impl term::Heaped for crate::data_structure::Nat {
            type Heap = crate::data_structure::Heap;
        }
    }
}
