[package]
name = "syn-insert-use"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
prettyplease = { workspace = true }
