[package]
name = "syn-insert-use"
version = { workspace = true }
edition = { workspace = true }
description = "Compress/de-obfuscate generated code by replacing fully-qualified paths with use statements"

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
prettyplease = { workspace = true }
