[package]
name = "syn-insert-use"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.100", features = ["full", "visit", "visit-mut"] }

[dev-dependencies]
prettyplease = "0.2.32"
