[package]
name = "std-parse-metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
langspec = { version = "0.1.0", path = "../../langspec" }
parse = { version = "0.1.0", path = "../../parse" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
syn = "2.0.98"
term = { version = "0.1.0", path = "../../term" }
