[package]
name = "std-parse-metadata"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
derivative = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
syn = { workspace = true }
langspec = { path = "../../langspec" }
parse = { path = "../../parse" }
term = { path = "../../term" }
