[package]
name = "term-of-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
extensionof-gen = { version = "0.1.0", path = "../extensionof-gen" }
langspec = { version = "0.1.0", path = "../langspec" }
langspec-gen-util = { version = "0.1.0", path = "../langspec-gen-util" }
prettyplease = "0.2.25"
syn = "2.0.89"

[dev-dependencies]
langspec-examples = { path = "../langspec-examples" }
term-of = { path = "../term-of" }
