[package]
name = "memo-cache"
version.workspace = true
edition.workspace = true
description = "A data structure for memoization"

[dependencies]
bumpalo.workspace = true
expect-test.workspace = true
sha2.workspace = true
