[package]
name = "enumerate-random"
version.workspace = true
edition.workspace = true
description = "Random generation of terms in a language"

[dependencies]
rand.workspace = true
rand_distr.workspace = true
tymetafuncspec-core.path = "../tymetafuncspec-core"
