[package]
name = "tree-identifier"
version.workspace = true
edition.workspace = true
description = "Trees of tokens that can be losslessly converted to and from camel, snake, and kebab identifiers"

[dependencies]
arbitrary.workspace = true
expect-test.workspace = true
proc-macro2.workspace = true
rand.workspace = true
serde.workspace = true
syn.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
