[package]
name = "term-pattern-match-strategy-provider-impl-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
langspec-gen-util = { version = "0.1.0", path = "../langspec-gen-util" }
langspec = { version = "0.1.0", path = "../langspec" }
prettyplease = "0.2.24"
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = "2.0.82"
term-trait-gen = { version = "0.1.0", path = "../term-trait-gen" }
term-specialized-gen = { version = "0.1.0", path = "../term-specialized-gen" }
words = { version = "0.1.0", path = "../words" }

[dev-dependencies]
langspec-examples = { path = "../langspec-examples" }
tymetafuncspec-core = { path = "../tymetafuncspec-core" }
term = { path = "../term" }
