[package]
name = "term-pattern-match-strategy-provider-impl-gen"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
codegen-component = { path = "../codegen-component" }
extension-autobox = { path = "../extension-autobox" }
langspec-gen-util = { path = "../langspec-gen-util" }
langspec = { path = "../langspec" }
term-pattern-match-strategy-provider-gen = { path = "../term-pattern-match-strategy-provider-gen" }
term-trait-gen = { path = "../term-trait-gen" }
term-specialized-gen = { path = "../term-specialized-gen" }
words = { path = "../words" }
term-specialized-impl-gen = { path = "../term-specialized-impl-gen" }
syn-insert-use = { path = "../syn-insert-use" }
prettyplease = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
langspec-examples = { path = "../langspec-examples" }
tymetafuncspec-core = { path = "../tymetafuncspec-core" }
term = { path = "../term" }
