[package]
name = "term-pattern-match-strategy-provider-impl-gen"
version = { workspace = true }
edition = { workspace = true }
description = "Generation of trait implementations needed by a pmsp"

[dependencies]
codegen-component = { path = "../codegen-component" }
langspec-gen-util = { path = "../langspec-gen-util" }
langspec = { path = "../langspec" }
rustgen-utils = { path = "../rustgen-utils" }
term-specialized-gen = { path = "../term-specialized-gen" }
words = { path = "../words" }
term-specialized-impl-gen = { path = "../term-specialized-impl-gen" }
syn = { workspace = true }

[dev-dependencies]
langspec-examples = { path = "../langspec-examples" }
tymetafuncspec-core = { path = "../tymetafuncspec-core" }
term = { path = "../term" }
