[package]
name = "pattern-tmf"
version.workspace = true
edition.workspace = true

[dependencies]
functor_derive = { workspace = true }
langspec = { path = "../langspec" }
once_cell = { workspace = true }
term = { path = "../term" }
tymetafuncspec-core.path = "../tymetafuncspec-core"
syn = { workspace = true }
derivative = { workspace = true }
ccf = { version = "0.1.0", path = "../ccf" }
to-literal = { version = "0.1.0", path = "../to-literal" }
serde.workspace = true
string-interner.workspace = true
covisit = { version = "0.1.0", path = "../covisit" }
pmsp = { version = "0.1.0", path = "../pmsp" }
parse-adt = { version = "0.1.0", path = "../parse-adt" }
visit = { version = "0.1.0", path = "../visit" }
unparse-adt = { version = "0.1.0", path = "../unparse-adt" }
