[package]
name = "pattern-dyn"
version.workspace = true
edition.workspace = true
description = "Untyped representation of patterns"

[dependencies]
ccf = { version = "0.1.0", path = "../ccf" }
derivative.workspace = true
langspec = { version = "0.1.0", path = "../langspec" }
names-langspec-sort = { version = "0.1.0", path = "../names-langspec-sort", package = "names-langspec-sort" }
pmsp = { version = "0.1.0", path = "../pmsp" }
syn.workspace = true
term = { version = "0.1.0", path = "../term" }
thiserror.workspace = true
to-literal = { version = "0.1.0", path = "../to-literal" }
tymetafuncspec-core = { version = "0.1.0", path = "../tymetafuncspec-core" }
visit = { version = "0.1.0", path = "../visit" }
words = { version = "0.1.0", path = "../words" }
