[package]
name = "tymetafuncspec-core"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
functor_derive = { workspace = true }
langspec = { path = "../langspec" }
term = { path = "../term" }
once_cell = { workspace = true }
serde = { workspace = true }
syn = { workspace = true }
derivative = { workspace = true }
slab = { workspace = true }
ccf = { version = "0.1.0", path = "../ccf" }
