[dependencies.ccf]
path = "../.././ccf"

[dependencies.file-tmf]
path = "../.././file-tmf"

[dependencies.parse]
path = "../.././parse"

[dependencies.parse-adt]
path = "../.././parse-adt"

[dependencies.parse-gen]
path = "../.././parse-gen"

[dependencies.pattern-tmf]
path = "../.././pattern-tmf"

[dependencies.pmsp]
path = "../.././pmsp"

[dependencies.term]
path = "../.././term"

[dependencies.term-pattern-match-strategy-provider-gen]
path = "../.././term-pattern-match-strategy-provider-gen"

[dependencies.term-trait-gen]
path = "../.././term-trait-gen"

[dependencies.tymetafuncspec-core]
path = "../.././tymetafuncspec-core"

[dependencies.typenum]
workspace = true

[dependencies.words]
path = "../.././words"

[package]
edition = "2024"
name = "fib-pat"
version = "0.0.0"
