[dependencies.ccf]
path = "../.././ccf"

[dependencies.covisit]
path = "../.././covisit"

[dependencies.fib-pat]
path = "../fib-pat"

[dependencies.fib-pat-ds]
path = "../fib-pat-ds"

[dependencies.file-tmf]
path = "../.././file-tmf"

[dependencies.names-langspec-sort]
path = "../.././names-langspec-sort"

[dependencies.names-langspec-sort-gen]
path = "../.././names-langspec-sort-gen"

[dependencies.parse]
path = "../.././parse"

[dependencies.parse-adt]
path = "../.././parse-adt"

[dependencies.parse-gen]
path = "../.././parse-gen"

[dependencies.pattern-tmf]
path = "../.././pattern-tmf"

[dependencies.pmsp]
path = "../.././pmsp"

[dependencies.std-parse-error]
path = "../../langspec-std/std-parse-error"

[dependencies.std-parse-metadata]
path = "../../langspec-std/std-parse-metadata"

[dependencies.term]
path = "../.././term"

[dependencies.term-bridge-gen]
path = "../.././term-bridge-gen"

[dependencies.term-pattern-match-strategy-provider-gen]
path = "../.././term-pattern-match-strategy-provider-gen"

[dependencies.term-pattern-match-strategy-provider-impl-gen]
path = "../.././term-pattern-match-strategy-provider-impl-gen"

[dependencies.term-specialized-gen]
path = "../.././term-specialized-gen"

[dependencies.term-specialized-impl-gen]
path = "../.././term-specialized-impl-gen"

[dependencies.term-trait-gen]
path = "../.././term-trait-gen"

[dependencies.tymetafuncspec-core]
path = "../.././tymetafuncspec-core"

[dependencies.typenum]
workspace = true

[dependencies.words]
path = "../.././words"

[package]
edition = "2024"
name = "fib-pat-parse"
version = "0.0.0"
