/// generated by [langdatastructure_gen::refbased::generate]
mod data_structure {
    /// generated by [langdatastructure_gen::refbased::gen_heap]
    #[derive(Default)]
    pub struct Heap {
        plus: crate::data_structure::heap::Plus,
        left_operand: crate::data_structure::heap::LeftOperand,
        right_operand: crate::data_structure::heap::RightOperand,
        f: crate::data_structure::heap::F,
        sum: crate::data_structure::heap::Sum,
        nat: crate::data_structure::heap::Nat,
    }
    mod heap {
        /// generated by [langdatastructure_gen::refbased::alg_heapbak]
        #[derive(Default)]
        pub struct Plus {}
        /// generated by [langdatastructure_gen::refbased::alg_heapbak]
        #[derive(Default)]
        pub struct LeftOperand {}
        /// generated by [langdatastructure_gen::refbased::alg_heapbak]
        #[derive(Default)]
        pub struct RightOperand {}
        /// generated by [langdatastructure_gen::refbased::alg_heapbak]
        #[derive(Default)]
        pub struct F {}
        /// generated by [langdatastructure_gen::refbased::alg_heapbak]
        #[derive(Default)]
        pub struct Sum {
            pub set: tymetafuncspec_core::SetHeapBak<
                crate::data_structure::Heap,
                crate::data_structure::heap::Nat,
            >,
        }
        /// generated by [langdatastructure_gen::refbased::alg_heapbak]
        #[derive(Default)]
        pub struct Nat {
            pub nat_lit: tymetafuncspec_core::BoundedNatHeapBak<crate::data_structure::Heap>,
            pub f: tymetafuncspec_core::IdxBoxHeapBak<
                crate::data_structure::Heap,
                crate::data_structure::heap::F,
            >,
            pub plus: tymetafuncspec_core::IdxBoxHeapBak<
                crate::data_structure::Heap,
                crate::data_structure::heap::Plus,
            >,
        }
    }
    pub struct Plus {
        pub left_operand: crate::data_structure::LeftOperand,
        pub right_operand: crate::data_structure::RightOperand,
    }
    pub struct LeftOperand {
        pub nat: crate::data_structure::Nat,
    }
    pub struct RightOperand {
        pub nat: crate::data_structure::Nat,
    }
    pub struct F {
        pub nat: crate::data_structure::Nat,
    }
    pub struct Sum {
        pub set: tymetafuncspec_core::Set<crate::data_structure::Heap, crate::data_structure::Nat>,
    }
    pub enum Nat {
        NatLit(tymetafuncspec_core::BoundedNat<crate::data_structure::Heap>),
        F(tymetafuncspec_core::IdxBox<crate::data_structure::Heap, crate::data_structure::F>),
        Plus(tymetafuncspec_core::IdxBox<crate::data_structure::Heap, crate::data_structure::Plus>),
    }
}
