/// generated by [langdatastructure_gen::refbased::generate]
mod data_structure {
    /// generated by [langdatastructure_gen::refbased::gen_heap]
    #[derive(Default)]
    pub struct Heap();
    pub struct Plus {
        pub left_operand: crate::data_structure::LeftOperand,
        pub right_operand: crate::data_structure::RightOperand,
    }
    pub struct LeftOperand {
        pub nat: crate::data_structure::Nat,
    }
    pub struct RightOperand {
        pub nat: crate::data_structure::Nat,
    }
    pub struct F {
        pub nat: crate::data_structure::Nat,
    }
    pub struct Sum {
        pub set: tymetafuncspec_core::Set<crate::data_structure::Heap, crate::data_structure::Nat>,
    }
    pub enum Nat {
        NatLit(tymetafuncspec_core::BoundedNat<crate::data_structure::Heap>),
        F(crate::data_structure::F),
        Plus(crate::data_structure::Plus),
    }
}
