/// generated by langdatastructure_gen::idxbased
pub mod idxbased {
    pub struct Fib {
        pub plus: Vec<crate::idxbased::data::Plus>,
        pub f: Vec<crate::idxbased::data::F>,
        pub nat: Vec<crate::idxbased::data::Nat>,
    }
    pub(crate) mod data {
        pub struct Plus(pub usize, pub usize);
        pub struct F(pub usize);
        pub enum Nat {
            NatLit(usize),
            F(Box<usize>),
            Plus(Box<usize>),
        }
    }
    #[derive(Clone, Copy)]
    pub struct Plus(usize);
    #[derive(Clone, Copy)]
    pub struct F(usize);
    #[derive(Clone, Copy)]
    pub struct Nat(usize);
}
