[package]
name = "unparse-gen"
version.workspace = true
edition.workspace = true

[dependencies]
syn.workspace = true
extension-autobox = { path = "../extension-autobox" }
langspec = { path = "../langspec" }
langspec-gen-util = { path = "../langspec-gen-util" }
parse = { path = "../parse" }
syn-insert-use = { path = "../syn-insert-use" }
term-pattern-match-strategy-provider-gen = { path = "../term-pattern-match-strategy-provider-gen" }
term-pattern-match-strategy-provider-impl-gen = { path = "../term-pattern-match-strategy-provider-impl-gen" }
term-specialized-gen = { path = "../term-specialized-gen" }
term-specialized-impl-gen = { path = "../term-specialized-impl-gen" }
term-trait-gen = { path = "../term-trait-gen" }
words = { path = "../words" }
codegen-component = { version = "0.1.0", path = "../codegen-component" }
