/// generated by [idxbased_extensionof_gen]
pub mod idxbased_extension_of {
    impl crate::extension_of::LImpl for crate::data_structure::idxbased::Fib {
        type NatLit = crate::data_structure::idxbased::NatLit;
        type Plus = crate::data_structure::idxbased::Plus;
        type F = crate::data_structure::idxbased::F;
        type Nat = crate::data_structure::idxbased::Nat;
    }
    pub mod owned {
        impl crate::extension_of::owned::Plus for crate::data_structure::idxbased::Plus {
            type LImpl = crate::data_structure::idxbased::Fib;
            type Ref<'a> = Self;
            type RefMut<'a> = Self;
            fn new(
                l: &mut Self::LImpl,
                args: (
                    <Self::LImpl as crate::extension_of::LImpl>::Nat,
                    <Self::LImpl as crate::extension_of::LImpl>::Nat,
                ),
            ) -> Self {
                let data = crate::data_structure::idxbased::data::Plus(args.0, args.1);
                let ret = l.plus.len();
                l.plus.push(data);
                Self(ret)
            }
            fn get_ref(self, _l: &Self::LImpl) -> Self::Ref<'_> {
                self
            }
            fn get_mut(self, _l: &mut Self::LImpl) -> Self::RefMut<'_> {
                self
            }
        }
        impl crate::extension_of::owned::F for crate::data_structure::idxbased::F {
            type LImpl = crate::data_structure::idxbased::Fib;
            type Ref<'a> = Self;
            type RefMut<'a> = Self;
            fn new(
                l: &mut Self::LImpl,
                args: (<Self::LImpl as crate::extension_of::LImpl>::Nat,),
            ) -> Self {
                let data = crate::data_structure::idxbased::data::F(args.0);
                let ret = l.f.len();
                l.f.push(data);
                Self(ret)
            }
            fn get_ref(self, _l: &Self::LImpl) -> Self::Ref<'_> {
                self
            }
            fn get_mut(self, _l: &mut Self::LImpl) -> Self::RefMut<'_> {
                self
            }
        }
    }
}
/// generated by [extensionof_gen]
pub mod extension_of {
    pub trait Projection<LImpl, const N: u8> {
        type To;
        fn project(self, l: &LImpl) -> Self::To;
    }
    pub trait LImpl {
        type NatLit: crate::extension_of::owned::NatLit;
        type Plus: crate::extension_of::owned::Plus;
        type F: crate::extension_of::owned::F;
        type Nat: crate::extension_of::owned::Nat;
    }
    pub trait ExtensionOf {
        type Any;
        fn take_reduct<L: ExtensionOf>(&self, term: &Self::Any) -> (L, L::Any);
    }
    pub mod owned {
        pub trait NatLit: Into<usize> + From<usize> {
            type Ref<'a>;
            type RefMut<'a>;
        }
        pub trait Plus {
            type LImpl: crate::extension_of::LImpl;
            type Ref<'a>;
            type RefMut<'a>;
            fn new(
                l: &mut Self::LImpl,
                args: (
                    <Self::LImpl as crate::extension_of::LImpl>::Nat,
                    <Self::LImpl as crate::extension_of::LImpl>::Nat,
                ),
            ) -> Self;
            fn get_ref(self, l: &Self::LImpl) -> Self::Ref<'_>;
            fn get_mut(self, l: &mut Self::LImpl) -> Self::RefMut<'_>;
        }
        pub trait F {
            type LImpl: crate::extension_of::LImpl;
            type Ref<'a>;
            type RefMut<'a>;
            fn new(
                l: &mut Self::LImpl,
                args: (<Self::LImpl as crate::extension_of::LImpl>::Nat,),
            ) -> Self;
            fn get_ref(self, l: &Self::LImpl) -> Self::Ref<'_>;
            fn get_mut(self, l: &mut Self::LImpl) -> Self::RefMut<'_>;
        }
        pub trait Nat {
            type LImpl: crate::extension_of::LImpl;
            type Ref<'a>;
            type RefMut<'a>;
            fn nat_lit(
                l: &mut Self::LImpl,
                from: <Self::LImpl as crate::extension_of::LImpl>::NatLit,
            ) -> Self;
            fn f(l: &mut Self::LImpl, from: <Self::LImpl as crate::extension_of::LImpl>::F)
                -> Self;
            fn plus(
                l: &mut Self::LImpl,
                from: <Self::LImpl as crate::extension_of::LImpl>::Plus,
            ) -> Self;
        }
    }
    pub mod reference {
        pub trait Plus<
            'a,
        >: Copy + crate::extension_of::Projection<
                Self::LImpl,
                0,
                To = <<Self::LImpl as crate::extension_of::LImpl>::Nat as crate::extension_of::owned::Nat>::Ref<
                    'a,
                >,
            > + crate::extension_of::Projection<
                Self::LImpl,
                1,
                To = <<Self::LImpl as crate::extension_of::LImpl>::Nat as crate::extension_of::owned::Nat>::Ref<
                    'a,
                >,
            > {
            type LImpl: crate::extension_of::LImpl;
            fn is_eq<'b: 'a>(self, l: &'b Self::LImpl, other: Self) -> bool;
        }
        pub trait F<
            'a,
        >: Copy + crate::extension_of::Projection<
                Self::LImpl,
                0,
                To = <<Self::LImpl as crate::extension_of::LImpl>::Nat as crate::extension_of::owned::Nat>::Ref<
                    'a,
                >,
            > {
            type LImpl: crate::extension_of::LImpl;
            fn is_eq<'b: 'a>(self, l: &'b Self::LImpl, other: Self) -> bool;
        }
        pub trait Nat<'a>: Copy {
            type LImpl: crate::extension_of::LImpl;
            fn nat_lit<'b: 'a>(
                self,
                l: &'b Self::LImpl,
            ) -> Option<
                <<Self::LImpl as crate::extension_of::LImpl>::NatLit as crate::extension_of::owned::NatLit>::Ref<
                    'a,
                >,
            >;
            fn f<'b: 'a>(
                self,
                l: &'b Self::LImpl,
            ) -> Option<
                <<Self::LImpl as crate::extension_of::LImpl>::F as crate::extension_of::owned::F>::Ref<
                    'a,
                >,
            >;
            fn plus<'b: 'a>(
                self,
                l: &'b Self::LImpl,
            ) -> Option<
                <<Self::LImpl as crate::extension_of::LImpl>::Plus as crate::extension_of::owned::Plus>::Ref<
                    'a,
                >,
            >;
            fn is_eq<'b: 'a>(self, l: &'b Self::LImpl, other: Self) -> bool;
        }
    }
    pub mod mut_reference {
        pub trait Plus<
            'a,
        >: Copy + crate::extension_of::Projection<
                Self::LImpl,
                0,
                To = <<Self::LImpl as crate::extension_of::LImpl>::Nat as crate::extension_of::owned::Nat>::RefMut<
                    'a,
                >,
            > + crate::extension_of::Projection<
                Self::LImpl,
                1,
                To = <<Self::LImpl as crate::extension_of::LImpl>::Nat as crate::extension_of::owned::Nat>::RefMut<
                    'a,
                >,
            > {
            type LImpl: crate::extension_of::LImpl;
        }
        pub trait F<
            'a,
        >: Copy + crate::extension_of::Projection<
                Self::LImpl,
                0,
                To = <<Self::LImpl as crate::extension_of::LImpl>::Nat as crate::extension_of::owned::Nat>::RefMut<
                    'a,
                >,
            > {
            type LImpl: crate::extension_of::LImpl;
        }
        pub trait Nat<'a>: Copy {
            type LImpl: crate::extension_of::LImpl;
            fn nat_lit<'b: 'a>(
                self,
                l: &'b mut Self::LImpl,
            ) -> Option<
                <<Self::LImpl as crate::extension_of::LImpl>::NatLit as crate::extension_of::owned::NatLit>::RefMut<
                    'b,
                >,
            >;
            fn f<'b: 'a>(
                self,
                l: &'b mut Self::LImpl,
            ) -> Option<
                <<Self::LImpl as crate::extension_of::LImpl>::F as crate::extension_of::owned::F>::RefMut<
                    'b,
                >,
            >;
            fn plus<'b: 'a>(
                self,
                l: &'b mut Self::LImpl,
            ) -> Option<
                <<Self::LImpl as crate::extension_of::LImpl>::Plus as crate::extension_of::owned::Plus>::RefMut<
                    'b,
                >,
            >;
            fn set<'b: 'a, 'c>(
                self,
                l: &'b mut Self::LImpl,
                value: <<Self::LImpl as crate::extension_of::LImpl>::Nat as crate::extension_of::owned::Nat>::Ref<
                    'c,
                >,
            );
        }
    }
}
pub mod data_structure {
    /// generated by [langdatastructure_gen::idxbased]
    pub mod idxbased {
        pub struct Fib {
            pub plus: Vec<crate::data_structure::idxbased::data::Plus>,
            pub f: Vec<crate::data_structure::idxbased::data::F>,
            pub nat: Vec<crate::data_structure::idxbased::data::Nat>,
        }
        pub(crate) mod data {
            pub struct Plus(
                pub crate::data_structure::idxbased::Nat,
                pub crate::data_structure::idxbased::Nat,
            );
            pub struct F(pub crate::data_structure::idxbased::Nat);
            pub enum Nat {
                NatLit(usize),
                F(Box<crate::data_structure::idxbased::F>),
                Plus(Box<crate::data_structure::idxbased::Plus>),
            }
        }
        pub type NatLit = usize;
        #[derive(Clone, Copy)]
        pub struct Plus(pub usize);
        #[derive(Clone, Copy)]
        pub struct F(pub usize);
        #[derive(Clone, Copy)]
        pub struct Nat(pub usize);
    }
}
